extends Node

signal fill_ammo(ammo_amount)
signal fill_fuel(fuel_amount)
signal repair_armor(armor_amount)
signal player_hurt(damage)
signal add_points(amount)
signal range_damage_dealt(amount)
signal melee_damage_dealt(amount)
signal enemy_died(where,stats)
signal add_exp(amount)
signal modify_player_stats(stat, modifier)
signal pause_game()
signal unpause_game()
signal take_upgrade(upgrade_name)
signal swap_can_shoot()
signal loss()
signal win()
